openapi: 3.0.0
info:
  title: KQI Platform API
  version: 1.0.0
paths:
  /agents:
    post:
      summary: Create a new trading agent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentConfig'
      responses:
        '201':
          description: Agent created
components:
  schemas:
    AgentConfig:
      type: object
      properties:
        name:
          type: string
        strategy:
          type: string
        risk_level:
          type: number
          format: float
      required: [name, strategy]
