# Run on PRs to main/develop and on pushes to feature branches
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Run isort (imports)
        run: isort .

      - name: Run Black (format)
        run: black --check .

      - name: Run mypy (type checks)
        run: mypy src/  
