on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 3 * * 0'  # Weekly on Sundays at 03:00 UTC

jobs:
  bandit:
    name: Bandit Security Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: bandit -r src/ -lll

  codeql:
    name: GitHub CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
