# JSON‐Schema (in YAML form) to validate default_hyperparameters.yaml
$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  risk_model:
    type: object
    properties:
      max_drawdown_threshold:
        type: number
        minimum: 0
        maximum: 1
      stop_loss_pct:
        type: number
        minimum: 0
        maximum: 1
    required: [max_drawdown_threshold, stop_loss_pct]

  strategy_model:
    type: object
    properties:
      learning_rate:
        type: number
        exclusiveMinimum: 0
      batch_size:
        type: integer
        minimum: 1
      num_epochs:
        type: integer
        minimum: 1
      network:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
            units:
              type: integer
              minimum: 1
            activation:
              type: string
          required: [type, units, activation]
    required: [learning_rate, batch_size, num_epochs, network]

  trade_model:
    type: object
    properties:
      slippage_tolerance:
        type: number
        minimum: 0
      max_open_positions:
        type: integer
        minimum: 1
    required: [slippage_tolerance, max_open_positions]

required: [risk_model, strategy_model, trade_model]
additionalProperties: false
